#!/bin/bash

pip install poetry --upgrade
poetry lock
poetry show --tree
poetry export -C $1 -f requirements.txt --without-hashes --with test --without dev -o $2'/test_requirements.txt'
cat $2'/test_requirements.txt'

pip install -r $2'/test_requirements.txt'

echo "beginning testing"
python -m pytest -s -v $1/tests