#!/bin/bash

echo $1
echo $2
echo $2'/test_requirements.txt'

pip install poetry --upgrade
poetry lock -C $1
poetry show -C $1 --tree
poetry export -C $1 -f requirements.txt --without-hashes --with test --without dev -o $2'/test_requirements.txt'
cat $2'/test_requirements.txt'

pip install -r $2'/test_requirements.txt'

echo "beginning testing"
python -m pytest -s -v $1/tests